// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentCar.API.Data;

#nullable disable

namespace RentCar.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251228045202_AddRequiredConstraints")]
    partial class AddRequiredConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RentCar.API.Models.LtPayment", b =>
                {
                    b.Property<string>("Payment_id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Payment_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payment_method")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rental_id")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Payment_id");

                    b.HasIndex("Rental_id");

                    b.ToTable("LtPayment", (string)null);
                });

            modelBuilder.Entity("RentCar.API.Models.MsCar", b =>
                {
                    b.Property<string>("Car_id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("License_plate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Number_of_car_seats")
                        .HasColumnType("int");

                    b.Property<decimal>("Price_per_day")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Car_id");

                    b.HasIndex("Status");

                    b.ToTable("MsCar", (string)null);
                });

            modelBuilder.Entity("RentCar.API.Models.MsCarImages", b =>
                {
                    b.Property<string>("Image_car_id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Car_id")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Image_link")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Image_car_id");

                    b.HasIndex("Car_id");

                    b.ToTable("MsCarImages", (string)null);
                });

            modelBuilder.Entity("RentCar.API.Models.MsCustomer", b =>
                {
                    b.Property<string>("Customer_id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Driver_license_number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone_number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Customer_id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("MsCustomer", (string)null);
                });

            modelBuilder.Entity("RentCar.API.Models.MsEmployee", b =>
                {
                    b.Property<string>("Employee_id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<decimal>("Email")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Name")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone_number")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Employee_id");

                    b.ToTable("MsEmployee", (string)null);
                });

            modelBuilder.Entity("RentCar.API.Models.TrMaintenance", b =>
                {
                    b.Property<string>("Maintenance_id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Car_id")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Employee_id")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("Maintenance_date")
                        .HasColumnType("datetime2");

                    b.HasKey("Maintenance_id");

                    b.HasIndex("Car_id");

                    b.HasIndex("Employee_id");

                    b.ToTable("TrMaintenance", (string)null);
                });

            modelBuilder.Entity("RentCar.API.Models.TrRental", b =>
                {
                    b.Property<string>("Rental_id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Car_id")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Customer_id")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("Payment_status")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Rental_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Return_date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Total_price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Rental_id");

                    b.HasIndex("Car_id");

                    b.HasIndex("Customer_id");

                    b.HasIndex("Payment_status");

                    b.HasIndex("Rental_date");

                    b.ToTable("TrRental", (string)null);
                });

            modelBuilder.Entity("RentCar.API.Models.LtPayment", b =>
                {
                    b.HasOne("RentCar.API.Models.TrRental", "Rental")
                        .WithMany("Payments")
                        .HasForeignKey("Rental_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rental");
                });

            modelBuilder.Entity("RentCar.API.Models.MsCarImages", b =>
                {
                    b.HasOne("RentCar.API.Models.MsCar", "Car")
                        .WithMany("CarImages")
                        .HasForeignKey("Car_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("RentCar.API.Models.TrMaintenance", b =>
                {
                    b.HasOne("RentCar.API.Models.MsCar", "Car")
                        .WithMany("Maintenances")
                        .HasForeignKey("Car_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentCar.API.Models.MsEmployee", "Employee")
                        .WithMany("Maintenances")
                        .HasForeignKey("Employee_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("RentCar.API.Models.TrRental", b =>
                {
                    b.HasOne("RentCar.API.Models.MsCar", "Car")
                        .WithMany("Rentals")
                        .HasForeignKey("Car_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentCar.API.Models.MsCustomer", "Customer")
                        .WithMany("Rentals")
                        .HasForeignKey("Customer_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("RentCar.API.Models.MsCar", b =>
                {
                    b.Navigation("CarImages");

                    b.Navigation("Maintenances");

                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("RentCar.API.Models.MsCustomer", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("RentCar.API.Models.MsEmployee", b =>
                {
                    b.Navigation("Maintenances");
                });

            modelBuilder.Entity("RentCar.API.Models.TrRental", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
